# Generated by Django 4.0.6 on 2022-08-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='workExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('company', models.CharField(blank=True, max_length=60, null=True)),
                ('current', models.BooleanField()),
                ('start_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
