# Generated by Django 4.0.6 on 2022-08-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
