# Generated by Django 4.0.6 on 2022-08-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_workexperience_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
