# Generated by Django 4.0.6 on 2022-09-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_workexperience_end_date_workexperience_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=60, null=True)),
                ('course_code', models.CharField(blank=True, max_length=60, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=60, null=True)),
                ('date_issued', models.DateField()),
                ('cert_id', models.CharField(blank=True, max_length=60, null=True)),
                ('valid_cert_link', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
