# Generated by Django 4.0.6 on 2022-09-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_certificates_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='image',
            field=models.ImageField(default='uploads/certs/ai.png', upload_to='uploads/certs'),
        ),
    ]
