# Generated by Django 4.0.6 on 2022-10-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_certificates_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificates',
            options={'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name_plural': 'Work Experience'},
        ),
    ]
