# Generated by Django 4.0.6 on 2022-07-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedoc',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
