# Generated by Django 4.0.6 on 2022-08-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0003_doctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctype',
            name='codedoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctype', to='knowledgebase.codedoc'),
        ),
    ]
