# Generated by Django 4.0.6 on 2022-08-05 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_alter_doctype_codedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctype',
            name='codedoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codedoc', to='knowledgebase.codedoc'),
        ),
    ]
