# Generated by Django 4.0.6 on 2022-08-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0006_alter_doctype_codedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctype',
            name='codedoc',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='knowledgebase.codedoc', verbose_name='Codedoc'),
        ),
    ]
