# Generated by Django 4.0.6 on 2022-08-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0008_rename_codedoc_doctype_codedoc_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codedoc',
            old_name='slug',
            new_name='codedoc_slug',
        ),
        migrations.RenameField(
            model_name='doctype',
            old_name='slug',
            new_name='doctype_slug',
        ),
    ]
