# Generated by Django 4.0.6 on 2022-08-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0010_rename_codedoc_slug_codedoc_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctype',
            name='codedoc_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='knowledgebase.codedoc', verbose_name='Codedoc'),
        ),
    ]
