# Generated by Django 4.0.6 on 2022-08-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0011_alter_doctype_codedoc_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctype',
            old_name='codedoc_link',
            new_name='codedoc',
        ),
    ]
