# Generated by Django 4.0.6 on 2022-08-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0012_rename_codedoc_link_doctype_codedoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctype',
            old_name='codedoc',
            new_name='codedocs',
        ),
    ]
