# Generated by Django 4.0.6 on 2022-08-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0014_alter_codedoc_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctype',
            old_name='codedocs',
            new_name='codedoc',
        ),
    ]
