# Generated by Django 4.0.6 on 2022-10-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0016_tutorial_tutorialcategory_tutorialseries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=200)),
                ('document_content', models.TextField()),
                ('document_published', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
