# Generated by Django 4.0.6 on 2022-10-08 19:23

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0017_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_article',
            field=djrichtextfield.models.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
