# Generated by Django 4.0.6 on 2022-10-09 05:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0018_documents_document_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_article',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
